version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=sqlite:////app/db/app.db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_HOST=mongod
      - MONGO_PORT=27017
    volumes:
      - ./db:/app/db
    depends_on:
      - redis
      - mongod

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server

  mongod:
    image: mongo:latest
    container_name: mongod
    ports:
      - "27017:27017"
    command: mongod
